mkdir "%~dp0..\..\user\ssl\root"
mkdir "%~dp0..\..\user\ssl\default"
del /Q "%~dp0..\..\user\ssl\root\rootCA.key"
del /Q "%~dp0..\..\user\ssl\root\rootCA.crt"
del /Q "%~dp0..\..\user\ssl\default\cert.key"
del /Q "%~dp0..\..\user\ssl\default\cert.csr"
del /Q "%~dp0..\..\user\ssl\default\cert.crt"
set "OPENSSL_CONF=%~dp0openssl.cnf"
"%~dp0openssl.exe" ecparam -genkey -name prime256v1 -out "%~dp0..\..\user\ssl\root\rootCA.key"
"%~dp0openssl.exe" req -x509 -new -sha256 -key "%~dp0..\..\user\ssl\root\rootCA.key" -days 3650 -out "%~dp0..\..\user\ssl\root\rootCA.crt" -subj "/emailAddress=root@ospanel.local/C=EU/stateOrProvinceName=Local Network/O=Open Server Panel/CN=Open Server Panel Root CA"
"%~dp0openssl.exe" ecparam -genkey -name prime256v1 -out "%~dp0..\..\user\ssl\default\cert.key"
"%~dp0openssl.exe" req -new -sha256 -key "%~dp0..\..\user\ssl\default\cert.key" -out "%~dp0..\..\user\ssl\default\cert.csr" -subj "/emailAddress=root@ospanel.local/C=EU/stateOrProvinceName=Local Network/O=Open Server Panel/CN=Default Certificate"
"%~dp0openssl.exe" x509 -req -sha256 -days 3650 -in "%~dp0..\..\user\ssl\default\cert.csr" -signkey "%~dp0..\..\user\ssl\default\cert.key" -out "%~dp0..\..\user\ssl\default\cert.crt"
certutil.exe -user -addstore "Root" "%~dp0..\..\user\ssl\root\rootCA.crt"
