# Block access to hidden files and folders except .well-known

<LocationMatch "/\.(?!well-known)">
    Require all denied
</LocationMatch>

<LocationMatch "^/(bitrix|local)/.+/\.">
    Require all granted
</LocationMatch>