    # include snippets/compression.conf;            # enable compression
    # include snippets/limits.conf;                 # connection and request rate limits
    # include snippets/force_https.conf;            # enforce HTTPS
    # include snippets/force_non_www.conf;          # redirect www → non-www
    # include snippets/block_hidden_files.conf;     # block hidden files and folders
    # include snippets/block_sensitive_files.conf;  # block backup/config/log files
    # include snippets/quiet_static_logs.conf;      # disable logs for favicon/robots    
    include snippets/maintenance_mode.conf;         # enable site-wide maintenance mode
    include snippets/friendly_errors.conf;          # enable friendly error pages
    # include snippets/disable_buffering.conf;      # disable fastcgi & proxy buffering
    # include snippets/security_fcgi_headers.conf;  # add security headers for fastcgi host
    # include snippets/fallback_redirect.conf;      # fallback to index.php

    location ~* \.(svg|png|jpe?g|gif|webp|avif|jxl|ico|tiff?|heic|css|js|mjs|map|webmanifest|wasm|json|jsonld|geojson|xml|txt|csv|pdf|eot|otf|ttf|ttc|woff2?|mp4|mov|webm|mpe?g|avi|ogv|mp3|wav|ogg|m4a|aac|mid|midi)$ {
        add_header Cache-Control "max-age=0, must-revalidate" always;
        try_files $uri =404;
    }

    # Enable directory listing
    autoindex on;

    index         index.php index.html index.htm;
    fastcgi_index index.php;

    location ~ \.php$ {
        fastcgi_pass $backend_ip:$backend_port;
        try_files    $fastcgi_script_name =404;
        include      fastcgi.conf;
        include      env/{host}.conf;
        # fastcgi_param  COUNTRY_CODE    $geoip2_data_country_code;
        # fastcgi_param  COUNTRY_NAME    $geoip2_data_country_name;
    }
