    # include snippets/compression.conf;            # enable compression
    # include snippets/limits.conf;                 # connection and request rate limits
    # include snippets/force_https.conf;            # enforce HTTPS
    # include snippets/force_non_www.conf;          # redirect www → non-www
    # include snippets/block_hidden_files.conf;     # block hidden files and folders
    # include snippets/block_sensitive_files.conf;  # block backup/config/log files
    # include snippets/quiet_static_logs.conf;      # disable logs for favicon/robots
    include snippets/maintenance_mode.conf;         # enable site-wide maintenance mode
    include snippets/friendly_errors.conf;          # enable friendly error pages
    # include snippets/security_headers.conf;       # add standard security headers for static fhost

    add_header Cache-Control "max-age=0, must-revalidate" always;

    # Enable directory listing
    autoindex on;

    index index.html index.htm;
