    # include snippets/compression.conf;            # enable compression
    # include snippets/limits.conf;                 # connection and request rate limits
    # include snippets/force_https.conf;            # enforce HTTPS
    # include snippets/force_non_www.conf;          # redirect www → non-www
    # include snippets/block_hidden_files.conf;     # block hidden files and folders
    # include snippets/block_sensitive_files.conf;  # block backup/config/log files
    # include snippets/quiet_static_logs.conf;      # disable logs for favicon/robots    
    include snippets/maintenance_mode.conf;         # enable site-wide maintenance mode
    include snippets/friendly_errors.conf;          # enable friendly error pages
    # include snippets/disable_buffering.conf;      # disable fastcgi & proxy buffering
    # include snippets/security_proxy_headers.conf; # add security headers for proxy host

    location ~* \.(svg|png|jpe?g|gif|webp|avif|jxl|ico|tiff?|heic|css|js|mjs|map|webmanifest|wasm|json|jsonld|geojson|xml|txt|csv|pdf|eot|otf|ttf|ttc|woff2?|mp4|mov|webm|mpe?g|avi|ogv|mp3|wav|ogg|m4a|aac|mid|midi)$ {
        add_header Cache-Control "max-age=0, must-revalidate" always;
        try_files $uri =404;
    }

    location / {
        proxy_http_version    1.1;
        proxy_cache_bypass    $http_upgrade $cookie_nocache $arg_nocache $http_pragma $http_authorization;
        proxy_pass            http://$backend_ip:$backend_port;
        proxy_redirect        http://$backend_ip:$backend_port/ /;
        proxy_set_header      Upgrade             $http_upgrade;
        proxy_set_header      Connection          $connection_upgrade;
        proxy_set_header      Host                $host;
        proxy_set_header      Accept-Encoding     "";
        proxy_set_header      X-Real-IP           $remote_addr;
        proxy_set_header      Forwarded           $proxy_add_forwarded;
        proxy_set_header      X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto   $scheme;
        proxy_set_header      X-Forwarded-Host    $host;
        proxy_set_header      X-Forwarded-Port    $server_port;
        proxy_set_header      X-Request-Id        $request_id;
        # proxy_set_header    X-Country-Code      $geoip2_data_country_code;
        # proxy_set_header    X-Country-Name      $geoip2_data_country_name;
    }
