[main]

additional_ssl_hosts     = 127.0.0.1
clean_directories        = {root_dir}\temp\{module_name}\{profile_name}
ignore_shutdown_all      = off
ip                       = auto
port                     = 25
log_directory            = {root_dir}\logs\{module_name}
log_level_values         = --quiet empty --verbose
log_level                = empty
ssl_auto_cert            = on
start_command            = "{root_dir}\modules\{module_name}\mailpit.exe" {log_level}
start_directory          = {root_dir}\modules\{module_name}
web_ui_url               = https://{module_name}
work_directories         = {root_dir}\data\{module_name}\{profile_name} {root_dir}\temp\{module_name}\{profile_name} {root_dir}\modules\{module_name}\config

allowed_system_env_vars  = auto
log_max_filesize         = auto
log_write_title          = auto
max_probation_fails      = auto
max_shutdown_time        = auto
probation                = auto
silent_mode              = auto
terminal_codepage        = auto
used_addons_environment  = auto

[env.bat]

comment                  = ::
destination              = {root_dir}\data\cli\env_{module_name}.bat
directory_separator      = \
enabled                  = on
encoding                 = UTF8
source_dir               = {root_dir}\system\templates

[MP_POP3_AUTH_FILE.txt]

destination              = {root_dir}\modules\{module_name}\config\MP_POP3_AUTH_FILE.txt
directory_separator      = \
enabled                  = off
encoding                 = UTF-8

[MP_SMTP_AUTH_FILE.txt]

destination              = {root_dir}\modules\{module_name}\config\MP_SMTP_AUTH_FILE.txt
directory_separator      = \
enabled                  = off
encoding                 = UTF-8

[MP_SMTP_FORWARD_CONFIG.txt]

destination              = {root_dir}\modules\{module_name}\config\MP_SMTP_FORWARD_CONFIG.txt
directory_separator      = \
enabled                  = off
encoding                 = UTF-8

[MP_SMTP_RELAY_CONFIG.txt]

destination              = {root_dir}\modules\{module_name}\config\MP_SMTP_RELAY_CONFIG.txt
directory_separator      = \
enabled                  = off
encoding                 = UTF-8

[MP_TAGS_CONFIG.txt]

destination              = {root_dir}\modules\{module_name}\config\MP_TAGS_CONFIG.txt
directory_separator      = \
enabled                  = off
encoding                 = UTF-8

[MP_UI_AUTH_FILE.txt]

destination              = {root_dir}\modules\{module_name}\config\MP_UI_AUTH_FILE.txt
directory_separator      = \
enabled                  = off
encoding                 = UTF-8

[environment]

MP_ALLOW_UNTRUSTED_TLS   = false
MP_API_CORS              = *
MP_BLOCK_REMOTE_CSS_AND_FONTS = false
MP_COMPRESSION           = 1
MP_DATABASE              = {root_dir}\data\{module_name}\{profile_name}\database.db
MP_DISABLE_HTTP_COMPRESSION = false
MP_DISABLE_VERSION_CHECK = true
MP_DISABLE_WAL           = false
MP_ENABLE_PROMETHEUS     = false
MP_ENABLE_SPAMASSASSIN   =
MP_HIDE_DELETE_ALL_BUTTON= false
MP_IGNORE_DUPLICATE_IDS  = false
MP_LABEL                 = DEV-MAIL
MP_LOG_FILE              = {root_dir}\logs\{module_name}\mailpit.log
MP_MAX_AGE               = 30d
MP_MAX_MESSAGES          = 0
MP_QUIET                 =
MP_TENANT_ID             =
MP_UI_AUTH               =
MP_UI_AUTH_FILE          =
MP_UI_BIND_ADDR          = {ip}:443
MP_UI_TLS_CERT           = {root_dir}\data\ssl\modules\{module_name}\cert.crt
MP_UI_TLS_KEY            = {root_dir}\data\ssl\modules\{module_name}\cert.key
MP_USE_MESSAGE_DATES     = false
MP_VERBOSE               =
MP_WEBROOT               = /

; Chaos

MP_CHAOS_TRIGGERS        =
MP_ENABLE_CHAOS          = false

; POP3 config

MP_POP3_AUTH             =
MP_POP3_AUTH_FILE        =
MP_POP3_BIND_ADDR        = 0.0.0.0:110
MP_POP3_TLS_CERT         = {root_dir}\data\ssl\modules\{module_name}\cert.crt
MP_POP3_TLS_KEY          = {root_dir}\data\ssl\modules\{module_name}\cert.key

; SEND API

MP_SEND_API_AUTH         =
MP_SEND_API_AUTH_ACCEPT_ANY = flase
MP_SEND_API_AUTH_FILE    =

; SMTP

MP_SMTP_ALLOWED_RECIPIENTS =
MP_SMTP_AUTH             =
MP_SMTP_AUTH_ACCEPT_ANY  = true
MP_SMTP_AUTH_ALLOW_INSECURE = false
MP_SMTP_AUTH_FILE        =
MP_SMTP_BIND_ADDR        = 0.0.0.0:25
MP_SMTP_DISABLE_RDNS     = true
MP_SMTP_IGNORE_REJECTED_RECIPIENTS =
MP_SMTP_MAX_RECIPIENTS   = 100
MP_SMTP_REQUIRE_STARTTLS = false
MP_SMTP_REQUIRE_TLS      = false
MP_SMTP_STRICT_RFC_HEADERS = false
MP_SMTP_TLS_CERT         = {root_dir}\data\ssl\modules\{module_name}\cert.crt
MP_SMTP_TLS_KEY          = {root_dir}\data\ssl\modules\{module_name}\cert.key

; SMTP forwarding

MP_SMTP_FORWARD_CONFIG   =

; SMTP relay

MP_SMTP_RELAY_ALL        = false
MP_SMTP_RELAY_CONFIG     =
MP_SMTP_RELAY_MATCHING   =

; Tagging

MP_TAG                   =
MP_TAGS_CONFIG           =
MP_TAGS_DISABLE          =
MP_TAGS_TITLE_CASE       = false
MP_TAGS_USERNAME         = false

; Webhook

MP_WEBHOOK_LIMIT         = 1
MP_WEBHOOK_URL           =

PATH                     = {root_dir}\modules\{module_name};%PATH%
TEMP                     = {root_dir}\temp\{module_name}\{profile_name}
TMP                      = {root_dir}\temp\{module_name}\{profile_name}
