# Enable brotli compression

brotli                           on;
brotli_comp_level                3;
brotli_min_length                1024;
brotli_static                    on;

# Enable gzip compression

gzip                             on;
gzip_comp_level                  3;
gzip_min_length                  1024;
gzip_static                      on;
