# friendly error pages

error_page 400 401 402 403 404 405 408 410 413 414 415 429 431 451 500 501 502 503 504 @error_pages;

location @error_pages {
    internal;
    root '../../system/error_pages';

    set $error_file /$status.html.$_error_lang;
    if (!-f $document_root$error_file) {
        set $error_file /$status.html.en;
    }

    rewrite ^ $error_file break;

    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    add_header Expires "Thu, 01 Jan 1970 00:00:01 GMT" always;
    add_header ETag "" always;
    add_header Last-Modified "" always;

    types {
        text/html html;
    }
    default_type text/html;
    charset utf-8;
}
