# Maintenance mode page

if (-f $document_root/maintenance.html) {
    set $_error_lang mt.$_error_lang;
    return 503;
}

if (-f $document_root/maintenance.txt) {
    set $_error_lang mt.$_error_lang;
    return 503;
}

if (-f $document_root/maintenance.flag) {
    set $_error_lang mt.$_error_lang;
    return 503;
}