# Hide security-related headers in proxied responses

proxy_hide_header Access-Control-Allow-Origin;
proxy_hide_header Referrer-Policy;
proxy_hide_header Timing-Allow-Origin;
proxy_hide_header X-Content-Type-Options;
proxy_hide_header X-Frame-Options;
proxy_hide_header X-Powered-By;
proxy_hide_header Content-Security-Policy;
proxy_hide_header Cross-Origin-Embedder-Policy;
proxy_hide_header Cross-Origin-Opener-Policy;
proxy_hide_header Cross-Origin-Resource-Policy;
proxy_hide_header Permissions-Policy;
proxy_hide_header Strict-Transport-Security;

include snippets/security_headers.conf;
