# Security-related response headers

# CORS Variant 1
# Preflight
# if ($is_options) {
#     if ($http_origin = "") {
#         return 403;
#     }
#     if ($is_preflight = 0) {
#         return 403;
#     }
#     if ($cors_allowed_origin = "") {
#         return 403;
#     }

#     add_header Access-Control-Allow-Origin      $cors_allowed_origin                            always;
#     add_header Access-Control-Allow-Credentials "true"                                          always;
#     add_header Access-Control-Allow-Methods     "GET, POST, PUT, PATCH, DELETE, OPTIONS"        always;
#     add_header Access-Control-Allow-Headers     "Content-Type, Authorization, X-Requested-With" always;
#     add_header Access-Control-Max-Age           "600"                                           always;
#     add_header Vary                             "Origin"                                        always;
#     return 204;
# }

# if ($cors_allowed_origin != "") {
#     add_header Access-Control-Allow-Origin $cors_allowed_origin always;
#     add_header Access-Control-Allow-Credentials "true" always;
#     add_header Vary "Origin" always;
# }

# CORS Variant 2
# add_header Access-Control-Allow-Origin  "*"                                always;

add_header Referrer-Policy                "strict-origin-when-cross-origin"  always;
add_header Timing-Allow-Origin            "*"                                always;
add_header X-Content-Type-Options         "nosniff"                          always;
add_header X-Frame-Options                "SAMEORIGIN"                       always;
add_header X-Request-Id                   $request_id                        always;

# HSTS
# add_header Strict-Transport-Security    $hsts_header                       always;

# add_header Content-Security-Policy      "default-src 'self'; base-uri 'self'; connect-src 'self' https: wss:; font-src 'self' https: data:; form-action 'self'; frame-ancestors 'self'; frame-src 'self'; manifest-src 'self'; media-src 'self' https: data: blob:; object-src 'none'; script-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; style-src 'self' https: 'unsafe-inline'; worker-src 'self' blob:; upgrade-insecure-requests" always;
# add_header Permissions-Policy           "camera=(), microphone=(), geolocation=(), payment=(), usb=()" always;

# Disable external embedding if needed:

# add_header Cross-Origin-Embedder-Policy "require-corp"                     always;
# add_header Cross-Origin-Opener-Policy   "same-site"                        always;
# add_header Cross-Origin-Resource-Policy "same-site"                        always;
# add_header Content-Security-Policy "default-src 'self'; base-uri 'none'; connect-src 'self'; font-src 'self' data:; form-action 'self'; frame-ancestors 'self'; frame-src 'self'; manifest-src 'self'; media-src 'self' data: blob:; object-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; worker-src 'self' blob:; upgrade-insecure-requests" always;
