# Hide security-related headers in FastCGI responses

fastcgi_hide_header Access-Control-Allow-Origin;
fastcgi_hide_header Referrer-Policy;
fastcgi_hide_header Timing-Allow-Origin;
fastcgi_hide_header X-Content-Type-Options;
fastcgi_hide_header X-Frame-Options;
fastcgi_hide_header X-Powered-By;
fastcgi_hide_header Content-Security-Policy;
fastcgi_hide_header Cross-Origin-Embedder-Policy;
fastcgi_hide_header Cross-Origin-Opener-Policy;
fastcgi_hide_header Cross-Origin-Resource-Policy;
fastcgi_hide_header Permissions-Policy;
fastcgi_hide_header Strict-Transport-Security;

include snippets/security_headers.conf;
