[client]

plugin_dir              = "{root_dir}/modules/{module_name}/lib/plugin"
socket                  = {module_name}
user                    = root

[mysql]

no-beep
default-character-set   = utf8mb4
local_infile            = 1

[mysqld]

# General Settings

basedir                 = "{root_dir}/modules/{module_name}"
character_set_server    = utf8mb4
collation_server        = utf8mb4_unicode_ci
datadir                 = "{root_dir}/modules/{module_name}/ospanel_data/default_data"
default_storage_engine  = InnoDB
default_time_zone       = Etc/GMT-3
explicit_defaults_for_timestamp = 1
ft_min_word_len         = 3
lc_messages             = en_US
lc_messages_dir         = "{root_dir}/modules/{module_name}/share"
local_infile            = 1
lower_case_table_names  = 2
performance_schema      = 0
pid_file                = "{root_dir}/modules/{module_name}/temp/{module_name}.pid"
plugin_dir              = "{root_dir}/modules/{module_name}/lib/plugin"
secure_file_priv        = "{root_dir}/modules/{module_name}/temp"
server_id               = 1
socket                  = {module_name}
tmpdir                  = "{root_dir}/modules/{module_name}/temp"

mysqlx                  = 1
mysqlx_socket           = {module_name}-X

# Skip Settings

#skip-grant-tables
#skip-name-resolve
skip-networking
skip-log-bin

# Cache Settings

query_cache_limit       = 256K
query_cache_size        = 32M
query_cache_type        = 1

# Connection Settings

max_connections         = 128
max_connect_errors      = 32
thread_cache_size       = 8

# InnoDB Settings

innodb_buffer_pool_size = 512M
innodb_data_file_path   = ibdata1:12M:autoextend
innodb_data_home_dir    = "{root_dir}/modules/{module_name}/ospanel_data/default_data"
innodb_file_per_table   = 1
#innodb_force_recovery  = 1
innodb_log_file_size    = 128M

# Logging

general_log             = 0

# MyISAM Settings

key_buffer_size         = 32M
myisam_recover_options  = backup,force

# Table Settings

table_definition_cache  = 4096
table_open_cache        = 4096
max_heap_table_size     = 256M
tmp_table_size          = 256M

[myisamchk]

key_buffer_size         = 32M
tmpdir                  = "{root_dir}/modules/{module_name}/temp"

[mysqladmin]

no-beep
default-character-set   = utf8mb4

[mysqlcheck]

default-character-set   = utf8mb4

[mysqldump]

quick
quote_names

[mysqlimport]

default-character-set   = utf8mb4

[mysqlshow]

default-character-set   = utf8mb4
keys                    = 0
show-table-type         = 0
status                  = 0

