            ProxyFCGIBackendType     GENERIC
            ProxyFCGISetEnvIf "true" GATEWAY_INTERFACE "CGI/1.1"
            ProxyFCGISetEnvIf "true" QUERY_STRING      "%{reqenv:QUERY_STRING}"
            ProxyFCGISetEnvIf "true" REDIRECT_STATUS   "200"
            ProxyFCGISetEnvIf "%{reqenv:CONTENT_LENGTH}  != ''" CONTENT_LENGTH    "%{reqenv:CONTENT_LENGTH}"
            ProxyFCGISetEnvIf "%{reqenv:CONTENT_TYPE}    != ''" CONTENT_TYPE      "%{reqenv:CONTENT_TYPE}"
            ProxyFCGISetEnvIf "%{reqenv:PATH_INFO}       != ''" PATH_INFO         "%{reqenv:PATH_INFO}"
            ProxyFCGISetEnvIf "%{reqenv:REMOTE_ADDR}     != ''" REMOTE_ADDR       "%{reqenv:REMOTE_ADDR}"
            ProxyFCGISetEnvIf "%{reqenv:REMOTE_PORT}     != ''" REMOTE_PORT       "%{reqenv:REMOTE_PORT}"
            ProxyFCGISetEnvIf "%{reqenv:REQUEST_METHOD}  != ''" REQUEST_METHOD    "%{reqenv:REQUEST_METHOD}"
            ProxyFCGISetEnvIf "%{reqenv:REQUEST_SCHEME}  != ''" REQUEST_SCHEME    "%{reqenv:REQUEST_SCHEME}"
            ProxyFCGISetEnvIf "%{reqenv:REQUEST_URI}     != ''" REQUEST_URI       "%{reqenv:REQUEST_URI}"
            ProxyFCGISetEnvIf "%{reqenv:SERVER_ADDR}     != ''" SERVER_ADDR       "%{reqenv:SERVER_ADDR}"
            ProxyFCGISetEnvIf "%{reqenv:SERVER_NAME}     != ''" SERVER_NAME       "%{reqenv:SERVER_NAME}"
            ProxyFCGISetEnvIf "%{reqenv:SERVER_PORT}     != ''" SERVER_PORT       "%{reqenv:SERVER_PORT}"
            ProxyFCGISetEnvIf "%{reqenv:SERVER_PROTOCOL} != ''" SERVER_PROTOCOL   "%{reqenv:SERVER_PROTOCOL}"
            ProxyFCGISetEnvIf "%{reqenv:SERVER_SOFTWARE} != ''" SERVER_SOFTWARE   "%{reqenv:SERVER_SOFTWARE}"
            ProxyFCGISetEnvIf "true" !OPENSSL_CONF
            ProxyFCGISetEnvIf "true" !OPENSSL_WIN32_UTF8
            ProxyFCGISetEnvIf "true" !PATH
            ProxyFCGISetEnvIf "true" !SRVROOT
            ProxyFCGISetEnvIf "true" !TEMP
            ProxyFCGISetEnvIf "true" !TMP